### ISSUE TITLE
v2.0

### ISSUE THREAD

**Issue by znicholls** [znicholls/netcdf-scm#52]
- [x] improve csv writing (#57)
    - [x] lowercase column names on output csvs (turns out Title_Case is how it's meant to be, see [pyam's source](https://github.com/IAMconsortium/pyam/blob/1d60716f88688d6b13185d8e94abc92dcc617ba7/pyam/core.py#L1063))
    - [x] improve handling of scenario realisation and targetmip when crunching
- [x] crunch default land/ocean masks (#58)
    - [x] keep track of hemispheric land/ocean fractions in the process (#61)
- [x] crunch to netcdf-scm `.nc` format instead (#60 and #62 )
    - [x] multiple cubes in a single netcdf-file
    - [x] keep history from original cubes
    - [x] reader can read the file out into an ScmDataFrame
- [x] Alter `_convert_scm_timeseries_cubes_to_openscmdata` to use cf name as `variable` rather than `long_name` (#63)
- [x] Update logging so it's easier to find which file was trying to be crunched when the error occured (#64)
- [x] improve wrangling (#58 and #65)
    - [x] only write climate model blended tuningstrucs (i.e. maintain backwards-compatibility, but nothing new)
    - [x] instead, just offer ability to re-write csvs as SCEN7/`*.IN` style files
        - [x] make a custom 'human readable format' with Malte
        - [x] create `.MAG` writer in pymagicc (https://github.com/openclimatedata/pymagicc/pull/250)
        - [x] add wrangling options from netcdf-scm `.nc`
            - [x] to `.MAG` files with all data
            - [x] to `.IN` files with scope to extend to user choice about variable mapping, rebasing and timeseries averaging/cutting
                - [x] allow semi-custom header writing
                - [x] fix header writing in `.IN` files in pymagicc (https://github.com/openclimatedata/pymagicc/pull/252)
- [x] other hot fixes (#66)
    - [x] deprecate flat wrangling in favour of symlinks
    - [x] fix wrangling so it makes nested directories properly (ie always captures drs of source)
    - [x] include full paths in `source files` attribute of crunched nc files so version is captured too
    - [x] unify `drs` and `cube-type` flags
    - [x] codacy hotfix (see [here](https://app.codacy.com/app/znicholls/netcdf-scm/issues/index))
    - [x] get code coverage back up
- [x] fix bug in docs (cubes not being documented...) (#55)
- [x] #51
- [x] #56 (moved to v2.1)
- [x] tos, hfds crunching (#84)
- [x] remove all .nc files from repo history and add back in using git lfs only (#83)

@lewisjared add whatever you want
